#!/usr/bin/env python3
# Extract settings from property files from ~/.config/settings.cfg

import configparser

class Config():
    path = "/Users/stCarolas/.config/alfa/settings.cfg"
    section = "global"
    def get_config():
        config = configparser.ConfigParser()
        config.read(self.path)
        return config[self.section]