#!/usr/bin/env python3
from slackclient import SlackClient
from alfaproperties import Config
from listener import Listener

config = Config()

def get_client():
   return SlackClient(config.get_value("slack", "token"))

slack = get_client()

def on_message(message):
    print("message:", message)
    if 'notify' in message:
        need_to_send = message['notify'] == True
        if need_to_send:
            if slack.rtm_connect():
                channel = message['channel']
                message = message['message']
                slack.rtm_send_message(channel, message)

Listener(config.get_value("global", "reactor_for_listening")).add_listener("public", on_message)
