#!/usr/bin/env python3
import jenkinsapi
from listener import Listener
from jenkinsapi.jenkins import Jenkins
import json
from alfaproperties import Config

config = Config()
events = ['start job']

def get_server_instance():
    server = Jenkins(config.get_value("jenkins", "url"),
                     username = config.get_value("jenkins", "login"),
                     password = config.get_value("jenkins", "token"))
    print("jenkins getted")
    return server

def start_job(project_name):
    job_name = form_job_name(project_name)
    get_server_instance().build_job(job_name)
    print("build",job_name,"started")

def form_job_name(project_name):
    return project_name + "_dev"

def listen(message):
    if message['event'] in events:
        job = message['payload']['job']
        start_job(job)

reactor = Listener(config.get_value("global","reactor_for_listening"))
reactor.add_listener("public", listen)

# jenkins = get_server_instance()
# print(jenkins.version)
